# Generated by Django 4.2.2 on 2023-06-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='job_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
